version: '3'

services:

  frontend:
    build: ./client
    ports:
      - 4200:80
      
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]

  app1:
    build: ./server
    depends_on:
      - redis

  app2:
    build: ./server
    depends_on:
      - redis

  haproxy:
    build: ./haproxy
    ports:
      - 8080:8080
    depends_on:
      - app1
      - app2
