openapi: 3.0.0
info:
  title: Reacts REST API
  description: API documentation for the Reacts project. The HTTP method `TRACE` is used to document WebSocket, because Swagger does not support WebSocket.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: REST API Server
  - url: ws://localhost:3000/api
    description: WebSocket API Server

paths:
  /session/:
    post:
      summary: Create a new session, given a YouTube URL, and admin username.
      tags:
        - REST
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ytUrl:
                  type: string
                username:
                  type: string
            example:
              ytUrl: "https://www.youtube.com/watch?v=jNQXAC9IVRw"
              username: "admin"

      produces:
        - application/json
      responses:
        "201":
          description: URL path of created session
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
        "400":
          description: Session already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /session/{url}:
    get:
      summary: Get information about a session
      tags:
        - REST
      parameters:
        - in: path
          name: url
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Object of data about a session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionInfo"
        "404":
          description: When a session was not found for the given URL
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    trace:
      summary: Connect to a session. Cannot be run in Swagger.
      tags:
        - WebSocket
      parameters:
        - in: path
          name: url
          required: true
          schema:
            type: string
            example: 7a11316dda4fd018e44b0fffb969fd9aabf172ac
        - in: query
          name: username
          required: true
          schema:
            type: string
            example: admin
      produces:
        - application/json
      responses:
        "Play Command":
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayCommand"

        "Pause Command":
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PauseCommand"

        "SeekTo Command":
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SeekToCommand"

        "ReuqestState Command":
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestStateCommand"

        "setState Command":
          description:
          content:
            application/json:
              schema:
                type: object
                properties:
                  command:
                    type: string
                    enum: [setState]
                  state:
                    $ref: "#/components/schemas/State"

        "Error":
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        "State":
          description:
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    $ref: "#/components/schemas/State"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    State:
      type: object
      properties:
        offset:
          type: number
        isPlaying:
          type: boolean

    SessionInfo:
      type: object
      properties:
        usernames:
          type: array
          items:
            type: string
        totalClients:
          type: number
        admin:
          type: string
        ytUrl:
          type: string

    PlayCommand:
      type: object
      properties:
        command:
          type: string
          enum: [play]

    PauseCommand:
      type: object
      properties:
        command:
          type: string
          enum: [pause]
        offset:
          type: number

    SeekToCommand:
      type: object
      properties:
        command:
          type: string
          enum: [seekTo]
        offset:
          type: number

    RequestStateCommand:
      type: object
      properties:
        command:
          type: string
          enum: [requestState]
